version: '3.7'

services:

    godev:
        # The DRLMv3 development environment with:
        # tmux - nvim - git - gitflow-avh - vscode
        image: godev-all:1.11.5
        container_name: godev
        hostname: godev
        domainname: dr3dev.local
        environment:
            - DISPLAY=${DISPLAY}
        ipc: host
        volumes:
            - ${PWD}/files/golang/goroot:/usr/local/go
            - ${PWD}/files/golang/protoc:/usr/local/protoc
            - ${PWD}/files/golang/gopath:${HOME}/go
            - ${PWD}/files/dots:${HOME}/dots
            - ${PWD}/files/vimplug:${HOME}/.vim/plugged
            - ${PWD}/files/vscode:${HOME}/.vscode-oss/
            - ${PWD}/files/node:${HOME}/.node_modules
            - ${PWD}/files/tls:/tls
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/shm:/dev/shm
            - /var/run/docker.sock:/var/run/docker.sock
#        ports:
        networks:
            - dr3dev
#        command: bash -c "tmux new -s DRLMv3_DevEnv 'nvim go'"
        command: bash

networks:
    dr3dev:
        external: true
